# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Bishal Thapa | Senior Software Developer
email: bishalth.x@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Bishal Thapa is a Senior Software Developer with a broad range of interests in the tech world, primarily focused on software engineering.

baseurl: ""
url: "https://bishal.com.np"
liveUrl: "https://bishal.com.np"
twitter_username: bishalthapa_x
github_username:  bishalthapa-x

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate


permalink: /blog/:year/:month/:day/:title.html
# Pagination settings
paginate: 4
paginate_path: "/blog/page/:num"


# https://highlightjs.org/usage/
markdown: kramdown
highlighter: rouge

# custom archive
collections:
  category:
    output: true
    permalink: /category/:path/


